services:
  - type: web
    name: dinerestaurant
    env: java
    plan: free
    buildCommand: "mvn clean install"
    startCommand: "java -jar target/dinerestaurant-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: MONGODB_URI
        sync: false
